### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by arun-instructor** [dhadley6/fashion#1]
Dave,

This looks great! Very nice job on this. Here are a couple of recommendations:
- Make sure everything is in the right place. For example:

``` html
<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
```

The above code was outside of the head tag. It will work, but this is bad practice.
- You can make use of your nested selectors to clean up code like this:

``` html
<ul class="bottomnav">
      <li class="bottomnav-a bottomborder">Home</li>
      <li class="bottomnav-a bottomborder">Women's</li>
      <li class="bottomnav-a bottomborder">Men's</li>
      <li class="bottomnav-a bottomborder">On the Street</li>
      <li class="bottomnav-a bottomborder">The Catwalk</li>
      <li class="bottomnav-a bottomborder">AdWatch</li>
      <li class="bottomnav-a bottomborder">About</li>
      <li class="bottomnav-a">Tips</li>
    </ul>
```

This could be .bottomnav li {} in the CSS
- Usually you will want to use single-line CSS when you have only one property. This is bad practice:

``` css
.col-2 {width:16.6666666666%; background-color:#000;text-align: center;color: #FFF;border:#FFF 1px solid;float:left;box-sizing: border-box;overflow:hidden;padding: 10px 15px 10px 15px}
```
